version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: roster_royals
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    
  web:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://root:root@db:5432/roster_royals
      POSTGRES_DB: roster_royals
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
